version: '3'
services:
  service-spring:
    container_name: spring-service
    image: app-testing/spring-service
    build: .
    ports:
      - "9702:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  repository-mysql:
    container_name: mysql
    image: mysql:8.0.33
    ports:
      - "9702:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_testing
      - MYSQL_USER=app_testing
      - MYSQL_PASSWORD=app_testing