version: '3'
services:
  spring-service:
    container_name: spring-service
    image: app-testing/spring-service
    build: .
    ports:
      - "9797:9797"
    environment:
      - SPRING_PROFILES_ACTIVE=prod