version: 1.0
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DATABASE_URL=mysql2://root:root@db:5432/app_development
  db:
    image: mysql
    ports:
      - "5432:5432"